# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 537c2a3ae5e0dc47ab3d201f4519c3efec87d4e12c12f212e108378b4006d1820de0a7e060e5e9080fd5a2c148d6a6c2f7cc2b3ca812522108435e24e89115de

test:
  secret_key_base: 25343ce85e8daa0c08e0866aad177b635a6fd4ee2440ef84f6b9cfb656580378e9547d563310f40587bdff5c8b42bd077ae9e10b34374a34eedc1c56f74ac927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
